"""Everything the program says, in English: the terminal's language, word for
word what the commands said before WI17, and the application's when it is set
to English. See meetingtool/texts/__init__.py for how a text names its data
and what goes inside [[ ]]."""

TEXTS = {
    # ── Frames of the recording (meetingtool.frames) ────────────────────────
    "frames.inside_repository": "output folder {folder} is inside the git work tree {work_tree}; frames of a meeting "
                                "must live outside any repository",
    "frames.budget_too_small": "the frame budget must be at least 1",
    "frames.not_local": "recording {path} is not a local file",
    "frames.cannot_open": "cannot open recording {path}[[: {detail}]]",
    "frames.cannot_decode": "cannot decode recording {path}[[: {detail}]]",
    "transcript.word_unreadable": "cannot read the Word transcript {path}[[: {detail}]]",
    "transcript.unreadable": "cannot read the transcript {path}[[: {detail}]]",
    "transcript.not_a_file": "transcript {path} is not a file",
    "transcript.no_timed_line": "transcript {path} has no timed line (Teams 'Speaker   M:SS', a time alone on its "
                                "line, or '[HH:MM:SS]')",

    # ── Projects (meetingtool.projects) ─────────────────────────────────────
    "projects.inside_repository": "data folder {folder} is inside the git work tree {work_tree}; meeting data must "
                                  "live outside any repository",
    "projects.bad_identifier": "{project!r} is not a project identifier",
    "projects.missing": "project {project} does not exist in {folder}",
    "projects.needs_name": "a project needs a name",
    "projects.exists": "project {project} already exists in {folder}",
    "projects.needs_title": "a meeting needs a title",
    "projects.unreadable": "the record {file} cannot be read[[: {detail}]]; nothing was changed: fix it or "
                           "move it out of the project",
    "projects.busy": "another MeetingTool (the application or a command) has held the data folder {folder} "
                     "for more than {seconds:.0f} s; nothing was changed: try again when it ends",
    "meeting.bad_date": "meeting date {date!r} is not a valid YYYY-MM-DD date",

    # ── The Gemini key and the reading of the frames (meetingtool.reading) ──
    "credentials.not_windows": "the Gemini key is kept in the Windows Credential Manager; this system is not Windows",
    "credentials.unreadable": "the Windows Credential Manager could not be read (error {code})",
    "credentials.empty": "the key is empty; nothing was saved",
    "credentials.refused": "the Windows Credential Manager refused to save the key (error {code})",
    "credentials.cannot_delete": "the Windows Credential Manager could not delete the key (error {code})",
    "gemini.no_text": "Gemini's answer has no text ({kind})",
    "gemini.unfinished": "Gemini's answer did not finish normally (finishReason {finish})",
    "gemini.blocks": "Gemini's answer does not hold one block per frame {first}-{last}: missing {missing}, repeated "
                     "{repeated}, not sent {extra}",
    "gemini.reason.not_json": "the answer is not JSON",
    "gemini.reason.no_answer": "no answer ({kind})",
    "gemini.over_budget": "stopped before sending {what}: that request could cost up to US${worst:.2f}, and with "
                          "about US${spent:.2f} already spent it could go over the budget of US${budget:.2f}; nothing "
                          "was written{refused}",
    "gemini.before.no_answer": " (the attempt before got no answer[[: {reason}]])",
    "gemini.before.refused": " (the answer before was refused: {error})",
    "gemini.refused": "Gemini refused the request (HTTP {status})[[: {reason}]]",
    "gemini.no_answer": "Gemini did not answer {what} after {retries} retries ({label}[[: {reason}]]); nothing was "
                        "written",
    "gemini.bad_key": "the saved key has characters a Gemini key never has; save it again",
    "gemini.inside_repository": "folder {folder} is inside the git work tree {work_tree}; frames and what they show "
                                "must live outside any repository",
    "gemini.what.frames": "frames {first}-{last}",
    "gemini.no_frames": "no frame_*.jpg in {folder}",
    "gemini.chunk_too_small": "the chunk size must be at least 1",

    # ── The summary (meetingtool.summary.writer) ────────────────────────────
    "language.es": "Spanish",
    "language.en": "English",
    "summary.what": "the summary",
    "summary.subject": "the summary",
    "summary.retired.discovery": "both presales and requirements gathering",
    "summary.wrong_language": "{subject} is not in {language} ({wanted} common words of it, {other} of the other "
                              "language, quotes and code left out)",
    "summary.section_wrong_language": "the section '{heading}' is not in {language} ({wanted} common words of it, "
                                      "{other} of the other language, quotes, code and tables left out)",
    "summary.frames_missing": "the summary names frame(s) that are not in the frames folder: {names}",
    "summary.frame_range": "the summary names a range of frames instead of each frame on its own: {text}",
    "summary.frame_unbracketed": "the summary mentions a frame without its file name in square brackets: {text}",
    "summary.unfinished": "Gemini's summary did not finish normally (finishReason {finish})",
    "summary.section_count": "the summary has the section '{heading}' {count} times, not once",
    "summary.order": "the summary's sections are not in the required order",
    "summary.no_key_points": "the summary's '{heading}' section has no bullet point",
    "summary.empty_sections": "the summary has nothing under these section(s): {headings}",
    "summary.not_read": "the frames of {folder} have not been read yet: run python -m meetingtool.reading read "
                        "--frames <folder> first",
    "summary.retired_type": "meeting type {meeting_type!r} is no longer used: it covered {covered}; use {use}",
    "summary.unknown_type": "unknown meeting type {meeting_type!r}; one of {options}",
    "summary.unknown_language": "unknown language {language!r}; one of {options}",
    "summary.needs_title_and_date": "a meeting added to a project needs --title and --date",
    "summary.project": "project {project}[[: {error}]]",
    "summary.not_added": "{output} was written, but the meeting could not be added to project {project}[[: {error}]]",

    # ── Questions and answers (meetingtool.summary.qa) ──────────────────────
    "qa.what.register": "register",
    "qa.what.screen_reading": "reading of the screen",
    "qa.what.register_part": "the register (part {part} of {parts})",
    "qa.subject.register": "the register",
    "qa.where.question": "question {number}",
    "qa.where.knowledge": "the knowledge '{group}'",
    "qa.where.seen": "what was seen on screen",
    "qa.unfinished": "Gemini's {what} did not finish normally (finishReason {finish})",
    "qa.not_json": "Gemini's {what} is not JSON",
    "qa.not_object": "Gemini's {what} is not a JSON object",
    "qa.not_text": "{where}: '{key}' is not text",
    "qa.mentions_frame": "{where} mentions a frame",
    "qa.invented_date": "{where} writes a date the transcript does not say ({dates})",
    "qa.invented_figure": "{where} writes a figure nobody said in the meeting ({figures})",
    "qa.question_not_object": "{where} is not a JSON object",
    "qa.no_question": "{where} has no question",
    "qa.bad_status": "{where}: status {status!r} is not one of {options}",
    "qa.bad_minutes": "{where}: its minutes are not H:MM:SS",
    "qa.ends_before": "{where}: its answer ends ({end}) before it starts ({start})",
    "qa.after_end": "{where}: minute {end} is after the meeting's last turn ({last})",
    "qa.answers_not_list": "{where}: 'answers' is not a list",
    "qa.answer_not_object": "{where}: an answer is not a JSON object",
    "qa.answer_no_text": "{where}: an answer has no text",
    "qa.answer_stranger": "{where}: the answer is given to {speaker!r}, who did not speak in the meeting",
    "qa.no_answer_status": "{where}: no answer, and yet its status is {status}",
    "qa.asker_stranger": "{where}: raised by {speaker!r}, who did not speak in the meeting",
    "qa.quote_missing": "{where}: its verbatim fragment is not in the transcript between {start} and {end} (or has "
                        "fewer than {words} words)",
    "qa.screen_not_bool": "{where}: 'screen' is not true or false",
    "qa.screen_quote_missing": "{where} is marked on screen, but the words that show it are not in the transcript "
                               "between {start} and {end}",
    "qa.no_questions_list": "the register has no list of questions",
    "qa.refused": "{count} question(s) refused: {refusals}{more}",
    "qa.no_knowledge": "the register has no 'knowledge'",
    "qa.knowledge_not_list": "the register's knowledge '{group}' is not a list of text",
    "qa.seen_no_list": "what was seen on screen has no list of answers",
    "qa.seen_not_object": "what was seen on screen: an answer is not a JSON object",
    "qa.seen_stranger": "what was seen on screen is given to {identifier!r}, which is not an answer on screen with "
                        "frames",
    "qa.seen_twice": "what was seen on screen is given to {identifier} twice",
    "qa.seen_empty": "{identifier}: nothing is said of what was seen",
    "qa.seen_names_frame": "{identifier}: what was seen names a frame in its text",
    "qa.seen_frames_not_list": "{identifier}: 'frames' is not a list of file names",
    "qa.seen_frames_outside": "{identifier}: frame(s) outside its span or not read: {names}",
    "qa.seen_missing": "what was seen on screen is missing for {identifiers}",
    "qa.stage.register": "register {part}/{parts}",
    "qa.stage.kept": "{stage} (kept from an earlier run)",
    "qa.stage.frames": "frames",
    "qa.stage.seen": "seen on screen",
    "qa.stage_cost": "{stage} US${cost:.3f}",
    "qa.stopped": "{error}{before} [stopped at {stage} after {attempts} attempt(s) of it; about US${spent:.3f} spent "
                  "in all{done}; the register was not written]",
    "qa.stopped.before": "; the answer before was refused too: {refusal:.300}",
    "qa.stopped.done": ", of which {stages}",
    "qa.no_folder": "the folder {folder} does not exist",
    "qa.needs_speakers": "the transcript {path} names no speaker, and the register of questions and answers needs "
                         "who asked and who answered: write the summary instead (format summary)",

    # ── The Word report (meetingtool.report) ────────────────────────────────
    "layout.marker_not_alone": "{{informe}} must be alone on its line, with nothing else on it",
    "layout.toc_unreadable": "the table of contents cannot be read: insert it again in Word (References, Table of "
                             "Contents) and save the template",
    "layout.marker_misplaced": "{{informe}} must be alone on its line in the body, not in a table, header or footer",
    "layout.unknown_fields": "the template has {unknown}, which is not a field it knows; the fields are {{cliente}} "
                             "{{proyecto}} {{reunion}} {{fecha}} {{tipo}} (or {{client}} {{project}} {{meeting}} "
                             "{{date}} {{type}})",
    "layout.toc_no_result": "the table of contents cannot be read: its field has no result part",
    "report.active.unreadable": "{part}: is not readable XML, so what it holds is not known[[ ({detail})]]",
    "report.active.external": "{part}: an external {kind} ({target})",
    "report.active.embedded": "{part}: a {kind} ({target})",
    "report.active.field": "{part}: a {field} field",
    "report.active.unnamed_field": "{part}: a field whose name is not written out in the file (another field builds it), so what it is cannot be known",
    "report.active.compat_unknown": "{part}: {name}, which is not a known part of Markup Compatibility, so what Word would read is not known",
    "report.active.compat_structure": "{part}: {name} is not formed as Markup Compatibility defines it (a list of alternatives, each with the namespaces it requires, and one fallback last), so what Word would read is not known",
    "report.active.compat_prefix": "{part}: Markup Compatibility names {name}, which is not a prefix declared in the file or is one that Word understands, so what Word would read is not known",
    "report.active.hyperlink": "{part}: a hyperlink to {target}, which is not a web page (http, https), a mail address or a place in the document",
    "report.active.macros": "a macro-enabled content type, or a macro project",
    "report.macro_extension": "the template {name} can carry macros ({suffix}); save it in Word as .docx or .dotx",
    "report.not_word": "the template {name} is not a Word document or template (.docx or .dotx)",
    "report.cannot_open": "the template {name} cannot be opened[[: {detail}]]",
    "report.macros": "the template {name} carries macros; save it in Word as .docx or .dotx",
    "report.active": "the template {name} has content that Word would load or run from outside it when a report is "
                     "opened, or a field a template may not hold, and every report would carry it to the client:\n"
                     "  {items}\nRemove it in Word and save the template again (attach the Normal template, embed "
                     "pictures instead of linking them, delete linked fields and embedded objects). The only fields "
                     "a template may hold are {allowed}.",
    "report.active_in_report": "the report was not written: it would carry content that Word would load or run from "
                               "outside it when the client opens it, or a field a template may not hold:\n  {items}\n"
                               "The template that gave it must be corrected. The only fields a template may hold are "
                               "{allowed}.",
    "report.not_a_document": "the template {name} cannot be opened as a Word document[[: {detail}]]",
    "report.template_unusable": "the template {name} cannot be used: {error}",
    "report.problem.range": "line {line}: a range of frames; name each frame on its own: {text}",
    "report.problem.missing": "line {line}: {name} is not in {folder}",
    "report.problem.unnamed": "line {line}: a frame mention that names no frame file (expected "
                              "[frame_NNN_tHH-MM-SS.jpg]): {text}",
    "report.not_built": "the report was not built:\n  {problems}",
    "report.missing_sections": "the Word document is missing the section(s) {missing}; it was not delivered",
    "report.toc_mismatch": "the Word document's table of contents does not list exactly its sections; it was not "
                           "delivered",
    "report.fields_left": "the Word document still has {fields} unfilled; it was not delivered",
    "report.images_mismatch": "the Word document has {lacking} image(s) missing and {extra} unexpected; it was not "
                              "delivered",
    "report.inside_repository": "folder {folder} is inside the git work tree {work_tree}; the report is client data "
                                "and must live outside any repository",
    "report.no_summary": "there is no {summary} in {folder}: write the summary first with python -m "
                         "meetingtool.summary",
    "report.no_heading": "{path} has no section heading; it does not look like a summary",
    "report.unread_headings": "line(s) {lines} of {path} start with # but are not headings the report can read (a "
                              "heading starts the line with 1 to 6 # and has text); the report was not built",
    "report.frame_unembeddable": "the frame {name} cannot be embedded[[ ({detail})]]; the report was not built",
    "report.cannot_write": "the report could not be written in {folder}[[: {detail}]]",
    "report.cannot_replace": "{path} could not be replaced[[ ({detail})]]{hint}",
    "report.close_word": "; if it is open in Word, close it and try again",
    "report.no_project": "there is no project {project!r}; list them with python -m meetingtool.projects",
    "report.example_exists": "{path} already exists; name another file",

    # ── The application (meetingtool.app): its screens ──────────────────────
    "app.nav.projects": "Projects",
    "app.nav.settings": "Settings",
    "app.footer": "This page is served by your own machine: nothing you see leaves it, except what is sent to Gemini "
                  "when processing.",
    "app.detail": "Detail: {detail}",
    "app.day": "{month}/{day}/{year}",
    "app.error.cannot_show": "Cannot be shown",
    "app.col.project": "Project",
    "app.col.client": "Client",
    "app.col.folder": "Folder",
    "app.col.format": "Format",
    "app.col.cost": "Cost",
    "app.col.date": "Date",
    "app.col.meeting": "Meeting",
    "app.col.type": "Type",
    "app.col.stage": "Stage",
    "app.col.state": "State",
    "app.col.time": "Time",
    "app.col.paid": "Paid",
    "app.projects.title": "Projects",
    "app.projects.none": "There are no projects yet.",
    "app.projects.new": "New project",
    "app.projects.name": "Name",
    "app.projects.client": "Client",
    "app.projects.create": "Create the project",
    "app.loose.title": "Results without a project",
    "app.loose.hint": "Folders of your data folder with a summary made from the terminal, outside a project. They "
                      "are shown as they are; the application does not change them.",
    "app.project.client": "Client: {client}",
    "app.project.new_meeting": "New meeting",
    "app.project.meetings": "Meetings",
    "app.project.no_meetings": "There are no meetings yet.",
    "app.project.knowledge": "What the project already knows",
    "app.project.knowledge_hint": "What each meeting leaves and the next one reads.",
    "app.kept.title": "Kept from runs that failed",
    "app.kept.hint": "What was paid in a run that failed stays here, so that processing the same meeting "
                     "again (the same transcript and format) does not pay it again. Discarding it cannot be "
                     "undone.",
    "app.kept.discard": "Discard",
    "app.kept.confirm": "Discard what was kept of «{title}»? Processing it again would pay it again.",
    "app.type.presale": "Presale",
    "app.type.negotiation": "Sales or negotiation",
    "app.type.requirements": "Requirements gathering",
    "app.type.kickoff": "Project kickoff",
    "app.type.status": "Status",
    "app.type.technical": "Technical",
    "app.type.training": "Training",
    "app.type.discovery": "Discovery (former type)",
    "app.format.summary": "Summary",
    "app.format.qa": "Questions and answers",
    "app.language.es": "Spanish",
    "app.language.en": "English",
    "app.stage.frames": "Frames of the video",
    "app.stage.reading": "Reading of the frames",
    "app.stage.summary": "Summary",
    "app.stage.qa": "Questions and answers",
    "app.stage.report": "Word report",
    "app.stage.preparing": "Preparation",
    "app.stage.saving": "Saving the meeting in the project",
    "app.state.pending": "waiting",
    "app.state.running": "running",
    "app.state.done": "done",
    "app.state.skipped": "not needed",
    "app.state.failed": "failed",
    "app.cost.title": "What it cost",
    "app.cost.total_html": "<strong>{spent}</strong> of a ceiling of {ceiling}, in {seconds} s.",
    "app.frame.mention": "frame {clock}",
    "app.frame.caption": "Minute {clock}",
    "app.result.open_word": "Open the Word report",
    "app.result.download_word": "Download the Word report",
    "app.result.images": "{shown} images in the report, of {total} kept from the video.",
    "app.result.from_terminal": "This meeting was added from the terminal: its folder was not recorded in the "
                                "project, so this is what the project kept of it.",
    "app.result.no_summary": "(no summary)",
    "app.result.key_points": "Key points",
    "app.new.title": "New meeting",
    "app.new.meeting_title": "Title",
    "app.new.date": "Date",
    "app.new.transcript": "Transcript",
    "app.new.transcript_hint": "(the Teams .docx, or a .txt with [HH:MM:SS] lines)",
    "app.new.recording": "Video",
    "app.new.recording_hint": "(optional: without a video only questions and answers can be made)",
    "app.new.type": "Meeting type",
    "app.new.no_type": "No type",
    "app.new.language": "Language of the result",
    "app.new.meeting_language": "The meeting's",
    "app.new.qa_hint": "(each question with its whole answer)",
    "app.new.ceiling": "Spending ceiling in dollars",
    "app.new.ceiling_hint": "(if a stage could go over it, it is not sent)",
    "app.new.process": "Process",
    "app.job.title": "Processing",
    "app.job.loading": "Loading…",
    "app.job.hint": "You can leave this page open; if you close it, the work goes on while the MeetingTool window "
                    "stays open.",
    "app.settings.title": "Settings",
    "app.settings.language": "Language of the application",
    "app.settings.language_hint": "It changes everything the application says. The language of each summary is "
                                  "chosen apart, when the meeting is processed.",
    "app.settings.language_save": "Save the language",
    "app.company.title": "Company",
    "app.company.hint": "The name and the logo appear at the top of every screen and in the tab's name. The logo: a "
                        "PNG or JPG of up to 1 MB (an SVG is not accepted: it can carry code).",
    "app.company.name": "Company name",
    "app.company.name_hint": "(leave it empty to show none)",
    "app.company.save_name": "Save the name",
    "app.company.logo": "Logo",
    "app.company.logo_current": "The current logo:",
    "app.company.no_logo": "No logo.",
    "app.company.use_logo": "Use this logo",
    "app.company.remove_logo": "Remove the logo",
    "app.key.title": "Gemini key",
    "app.key.saved": "A key is saved ({length} characters). It is never shown.",
    "app.key.none": "No key is saved: without one nothing can be processed.",
    "app.key.hint": "It must belong to a Google Cloud project with billing enabled: on the free tier Google may use "
                    "what is sent to it, and meetings are client data. It is kept in the Windows Credential Manager.",
    "app.key.new": "New key",
    "app.key.save": "Save the key",
    "app.key.delete_confirm": "Delete the saved key?",
    "app.key.delete": "Delete the key",
    "app.template.title": "The company's Word template",
    "app.template.unusable": "The saved template can no longer be used: {problem}",
    "app.template.unusable_hint": "Upload another one, or stop using it so that reports come out with the neutral "
                                  "design.",
    "app.template.none": "No template: reports come out with a neutral design.",
    "app.template.named_html": "The company uses the template <strong>{name}</strong>, uploaded on {day}.",
    "app.template.unnamed": "The company uses a template uploaded before its name was kept: to see it here, upload "
                            "it again.",
    "app.field.client": "the client",
    "app.field.project": "the project",
    "app.field.meeting": "the meeting's title",
    "app.field.date": "the date",
    "app.field.type": "the meeting type",
    "app.template.fields": "On the cover it will put: {fields}.",
    "app.template.no_fields": "It has no data to fill on the cover (they are written in braces, for example "
                              "{{client}}).",
    "app.template.toc": "It has a table of contents: each report puts its sections there, without page numbers (in "
                        "Word, right-click the table and «Update Field» adds them).",
    "app.template.no_toc": "It has no table of contents.",
    "app.template.dropped_index_one": "What it has after the table of contents is a model and does not go into the "
                                      "reports: 1 paragraph with text.",
    "app.template.dropped_index": "What it has after the table of contents is a model and does not go into the "
                                  "reports: {count} paragraphs with text.",
    "app.template.dropped_marker_one": "What it has after {{report}} is a model and does not go into the reports: 1 "
                                       "paragraph with text.",
    "app.template.dropped_marker": "What it has after {{report}} is a model and does not go into the reports: "
                                   "{count} paragraphs with text.",
    "app.template.all_cover": "Everything written on its page comes out as the cover of each report.",
    "app.template.hint": "A .docx or .dotx (never one with macros) with the company's logo, header, colours and "
                         "fonts. What is written on its page is the cover of each report; where it writes {{client}}, "
                         "{{project}}, {{meeting}}, {{date}} or {{type}}, in braces, that data of the meeting goes. If "
                         "it has a Word table of contents, it is filled with the sections of each report, and what "
                         "comes after it (or after {{report}}, alone on its line) is a model that does not go in.",
    "app.template.example": "Download an example template",
    "app.template.example_after": " to start with.",
    "app.template.example_file": "example-template.docx",
    "app.template.file": "Template",
    "app.template.use": "Use this template",
    "app.template.remove": "Stop using the template",

    # ── The application: what it refuses or reports ────────────────────────
    "app.not_found": "there is nothing at this address",
    "app.unexpected": "something unexpected failed[[: {detail}]]",
    "app.refused.not_local": "only requests from this same machine are served",
    "app.refused.not_this_app": "the request is not for this application",
    "app.refused.other_site": "a request from another site is not served",
    "app.refused.session": "open the application from MeetingTool (the session is not valid)",
    "app.refused.change_page": "a change is only accepted from the application's page",
    "app.refused.json_only": "a change is only accepted as JSON",
    "app.refused.method": "method not allowed",
    "app.refused.stale_link": "this address is no longer valid: open the application again from MeetingTool",
    "app.refused.no_length": "the request's length is missing",
    "app.refused.too_big": "the request is too big",
    "app.refused.not_json": "the request is not valid JSON",
    "app.refused.not_object": "the request is not a JSON object",
    "app.refused.bad_file": "that file does not do: only {kinds} are accepted",
    "app.refused.no_file_length": "the file's length is missing",
    "app.refused.empty_or_big": "the file is empty or too big",
    "app.refused.cut": "the file arrived cut short",
    "app.request.bad_date": "the date {value!r} is not a valid YYYY-MM-DD date",
    "app.request.not_text": "the field {name} is not text",
    "app.request.no_project": "there is no project {project!r}",
    "app.request.needs_title": "the meeting needs a title",
    "app.request.no_type": "there is no meeting type {value!r}",
    "app.request.no_language": "there is no language {value!r}",
    "app.request.no_format": "there is no format {value!r}",
    "app.request.no_transcript": "the transcript is missing (a Teams .docx or a .txt with [HH:MM:SS] lines)",
    "app.request.video_gone": "the uploaded video is no longer there: upload it again",
    "app.request.qa_needs_speakers": "the register of questions and answers needs who asked and who answered, and "
                                     "this transcript names no speaker (each time stands alone on its line): "
                                     "choose the summary format",
    "app.request.summary_needs_video": "the summary needs the video, to read what was shown; without a video, choose "
                                       "the questions and answers format",
    "app.request.bad_ceiling": "the spending ceiling must be a number of dollars greater than 0 and up to 5",
    "app.request.project_not_text": "the name and the client are text",
    "app.run.no_key": "no Gemini key is saved: save it in Settings",
    "app.run.busy": "a meeting is already being processed: wait until it ends",
    "app.run.folder_taken": "there is already a folder {folder} in the project",
    "app.key.paste": "paste the key before saving it",
    "app.open.windows_only": "opening the Word report from here only works on Windows: download it",
    "app.data_folder_in_use": "MeetingTool is already open on {folder}: use that window",
    "app.settings.unknown_language": "there is no language {value!r} for the application",
    "app.company.name_not_text": "the company's name is text",
    "app.company.name_too_long": "the company's name can have up to {limit} characters",
    "app.company.name_unprintable": "the company's name has characters that cannot be shown",
    "app.logo.svg": "an SVG logo is not accepted, because it can carry code that would run inside the application: "
                    "save it as PNG or JPG",
    "app.logo.kind": "the logo must be a PNG or a JPG",
    "app.logo.too_big": "the logo is larger than 1 MB: make it smaller or save it as JPG",
    "app.logo.too_many_pixels": "the logo is too large: up to {limit} pixels a side",
    "app.logo.not_image": "the file is not a PNG or JPG image that can be read[[: {detail}]]",
    "app.console.open": "MeetingTool is open in your browser ({url}); only this machine can get in.",
    "app.console.paste": "If it did not open, paste this address in the browser: {url}",
    "app.console.keep": "Leave this window open while you use it; to close it, close this window or press Ctrl+C.",
    "app.console.error": "error: {error}",

    # ── The page's script (static/app.js), which fills in the {names} itself
    "js.unreadable": "the answer could not be read",
    "js.failed": "it could not be done",
    "js.upload_failed": "it could not be uploaded",
    "js.connection_lost": "the connection with MeetingTool was lost",
    "js.wait": "One moment…",
    "js.opening": "Opening the Word report…",
    "js.choose_template": "Choose the template.",
    "js.checking_template": "Checking the template…",
    "js.choose_logo": "Choose the logo.",
    "js.checking_logo": "Checking the logo…",
    "js.missing_transcript": "The transcript is missing.",
    "js.summary_needs_video": "The summary needs the video. Without a video, choose questions and answers.",
    "js.uploading_transcript": "Uploading the transcript…",
    "js.uploading_video": "Uploading the video… {percent} %",
    "js.starting": "Starting…",
    "js.col.stage": "Stage",
    "js.col.state": "State",
    "js.col.time": "Time",
    "js.col.cost": "Cost",
    "js.state.pending": "waiting",
    "js.state.running": "running…",
    "js.state.done": "done",
    "js.state.skipped": "not needed",
    "js.state.failed": "failed",
    "js.spent": "Spent: {spent} of a ceiling of {ceiling} · {seconds} s",
    "js.see_meeting": "See the meeting",
    "js.failed_at": "It failed at «{stage}»: {error}. The meeting was not added to the project and nothing was left "
                    "half done.",
    "js.detail": "Detail: {detail}",
    "js.retry": "Try again",
    "js.connection_job": "The connection with MeetingTool was lost: check that its window is still open.",
    "js.running": "«{title}» is being processed: see the progress",
    "js.kept": "What Gemini already answered for this meeting was kept ({paid} paid so far): processing it "
               "again with the same transcript does not pay that again. Until then, it is listed in the project.",
    "js.discard": "Discard what was kept",
    "js.discard_confirm": "Discard what was kept? Processing this meeting again would pay it again.",
    "js.discarded": "Discarded.",
}
